// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmq3XMAwgpCeA4H6zcweY5rxNV8SET5Zg',
    appId: '1:196803033655:web:1ad8177a2b93364ac09db2',
    messagingSenderId: '196803033655',
    projectId: 'e-commerceapp-93fd4',
    authDomain: 'e-commerceapp-93fd4.firebaseapp.com',
    storageBucket: 'e-commerceapp-93fd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgu9v0rRJWoavbe-8kjG9CHwpLzb1ibbk',
    appId: '1:196803033655:android:b4138e92db6d6a36c09db2',
    messagingSenderId: '196803033655',
    projectId: 'e-commerceapp-93fd4',
    storageBucket: 'e-commerceapp-93fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfzisDVM6raAfvIvxYK_wakCmocusC2M',
    appId: '1:196803033655:ios:a4b90b257df6d0bfc09db2',
    messagingSenderId: '196803033655',
    projectId: 'e-commerceapp-93fd4',
    storageBucket: 'e-commerceapp-93fd4.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );
}
